### ISSUE TITLE
Mark as compatible to Moodle 2.8 in Moodle plugins repo

### ISSUE THREAD

**Issue by abias** [moodlehu/moodle-mod_etherpadlite#16]
Hi,

we have verified that the plugin basically works in Moodle 2.8. Could you please mark the plugin as compatible to Moodle 2.8 on https://moodle.org/plugins/view/mod_etherpadlite?

Thanks,
Alex

**Comment by goldquest** [comment]
Did you check for warnings or deprecations?

**Comment by abias** [comment]
Yes, I did. 
In our installation, there were no PHP debug messages, otherwise you would have got a ticket about that :)

**Comment by goldquest** [comment]
Done ;)
