### ISSUE TITLE
Javascript error + Permission

### ISSUE THREAD

**Issue by nicolas-dalpe** [moodlehu/moodle-mod_etherpadlite#35]
Hi Everyone,
I installed etherpad-light plugin for Moodle and I get the following error. I am not sure how to fix it. Anyone saw this error before?

Also - maybe related to the error below - I always have the message "You do not have permission to access this pad" even though my user have every privilege set to "yes" in the activity.

I use Moodle 3.7.2, latest version of etherpad-light

Thank you in advance for your help

An error occurred
The error was reported with the following id: 'xxx'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: xxx
URL: https://etherpad.xxx.com/p/g.7m8d9NvVD5ActpNJ$XXXX
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
TypeError: pad.collabClient is null in https://etherpad.xxx.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
Chat 0

**Comment by grabs** [comment]
Hi Nicolas,
can you give us a bit more information about your setup?
e.g:
- How do you run etherpad?
- What moodle settings do you use to connect etherpad?
- Do you use on both systems the same main domain?
- Do you use a reverse proxy?
- Can you access etherpad without moodle?
...
Best regards
Andreas

**Comment by nicolas-dalpe** [comment]
Hi grabs,
thx for you reply.

How do you run etherpad?
 - I simply create a new Etherpad Light activity in my course. Does that answer your question?

What moodle settings do you use to connect etherpad?
 - See attachment

Do you use on both systems the same main domain?
 - No. We use the server on a subdomain and the Moodle on another subdomain

Do you use a reverse proxy?
 - No, we don't use proxy

Can you access etherpad without moodle?
 - Yes, this works fine.

Below is more info that might help you

My settings in Moodle
![Etherpad-Lite](https://user-images.githubusercontent.com/55551039/68782510-90142b00-0607-11ea-9bcd-ab64861cacf5.png)

The error in Moodle activity. This shows up for 1 or 2 seconds then it displays: "You do not have permission to access this pad"
![etherpad_error_js](https://user-images.githubusercontent.com/55551039/68782694-cbaef500-0607-11ea-989d-6f6bbd15304c.png)

The permission denied screen. I don't know if this is caused by the error because I have every permission set to "yes"
![etherpad_perm_denied](https://user-images.githubusercontent.com/55551039/68783455-04030300-0609-11ea-930d-4b95b829d751.png)


The full debug logs. You will find the error at line 1335 and 1407. I replaced our FQDN with properdomain.com for privacy.
[etherpad.log](https://github.com/moodlehu/moodle-mod_etherpadlite/files/3842267/etherpad.log)

Error in Firefox console
![etherpad_error_js_inspector](https://user-images.githubusercontent.com/55551039/68782869-0fa1fa00-0608-11ea-965f-bede8e7faab4.png)

Hope this helps

**Comment by grabs** [comment]
Hi Nicolas,,
how do you run etherpad and what version? I don't mean the moodle plugin ;).
Did you try to reach the etherpad installation directly from your moodle server (e.g. with wget)?

**Comment by nicolas-dalpe** [comment]
Hi grabs,
I start the server with the following command: ./opt/etherpad-lite/bin/run.sh --root
The server version is 1.6.6

I am not sure what you mean by "how do you run the server". If that does not answer your question, can you please rephrase your question or be more precise?

thx

**Comment by grabs** [comment]
Hi Nicolas,
what I mean is e.g.
Do you run etherpad on the same server as moodle
Do you run etherpad in a container

My other question was whether your server can access etherpad or not because moodle talks to etherpad from the server side too and not only from the client side.

The current version of etherpad lite is 1.7.x. Did you try this out?

**Comment by nicolas-dalpe** [comment]
@grabs FYI updating the server to version 1.8.0-beta.1 did the trick for us. 

thx

**Comment by grabs** [comment]
@nicolas-dalpe Thank your for this information! Good to hear.
I close this issue now.
Andreas

**Comment by mcbastian** [comment]
It might need reinvestigation. I have the same problem. Installed etherpad 1.8.4 (via git clone) and this module (via git clone). Moodle is 3.8.2.
EP-Moodle Config:
EPL is behind an apache proxy (mod_proxy). 2 Domains: 
moodle.domain.de and etherpad.domain.de
Cookie Domain is set to ".domain.de"
API key is verified to match the APIKEY.txt from Etherpad. 
Etherpad works fine when accessed via https://etherpad.domain.de
Accessing via moodle results in the following output on the etherpad console log
`
[2020-05-28 10:25:56.942] [INFO] API - REQUEST, v1.1:createAuthorIfNotExistsFor, {"authorMapper":"2","name":"Admin User","apikey":"MYWONDERFULAPIKEYHERE"}
[2020-05-28 10:25:56.943] [INFO] API - RESPONSE, createAuthorIfNotExistsFor, {"code":0,"message":"ok","data":{"authorID":"a.RANDOMLETTERS"}}
[2020-05-28 10:25:56.962] [INFO] API - REQUEST, v1.1:createSession, {"groupID":"0","authorID":"a.SAMERANDOMLETTERS","validUntil":"1590665156","apikey":"MYWONDERFULAPIKEYHERE"}
[2020-05-28 10:25:58.524] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"0","sessionID":"null","password":null,"token":"t.DIFFERENTRANDOMLETTERS","protocolVersion":2}
`

Result in moodle is the screen saying "You do not have permission to access this pad."

Cheers,
Sebastian

**Comment by grabs** [comment]
Hi Sebastian,
did you create a new etherpad instance in your course or did you use an already existing instance?
The padId = 0 suggests there is no pad assigned to the instance.
Can you check this again by creating a new instance?
Best regards
Andreas

**Comment by mcbastian** [comment]
Hi Andreas,
it's working now. It was a bit more involved to get it running but using your suggestions:

I tried creating a new pad, same problem. But after I deleted the pad and the database in EPL and created a new empty DB and adding a new Pad in Moodle, it now works!
Thanks for your help!

Cheers, Sebastian

**Comment by grabs** [comment]
In conclusion, I'd say that there was no problem with the Moodle plugin itself but with the etherpad structure. So I can close this issue.

**Comment by bellzebub** [comment]
Hi I have the Problem too. 
I tried an working etherpad instance on ubuntu and a working etherpad in windows. But on both i get the same error message:
![grafik](https://user-images.githubusercontent.com/71334846/93234340-750ccd00-f77c-11ea-9a19-1de99f606e54.png)
on the Etherpad server ( ver.: 1.8.5) and on moodle ( ver. 3.9) I get the message "You do not have the permission to access the Pad".

Thanks
Frank

**Comment by grabs** [comment]
Hi Frank,

where did you get your etherpad server from? I had this problem too while I accidentally cloned the `develop` branch.
In my install script I have a line like this:
`cd /opt && git clone https://github.com/ether/etherpad-lite.git etherpad`
This checkes out the `develop` branch which is the wrong revision.
Since I tried this:
`cd /opt && git clone https://github.com/ether/etherpad-lite.git etherpad && cd etherpad && git checkout -b v185 1.8.5`
the error was gone.
In most situations the `develop` branch is fine but in a production environment you should use the correct revision by using the tag `1.8.5` or what ever version is the most recent.

I hope this helps a little.

Best regards
Andreas

**Comment by bellzebub** [comment]
Hi and thx for the fast response.
So I updated the Etherpad to 1.8.6 (not the develop branch). And the authentication failure is gone. 
But now I get the following 
![failure](https://user-images.githubusercontent.com/71334846/94427584-9f548680-018f-11eb-935a-d6e97a363d34.jpg)

The normal Etherpad is running fine.

Thanks
Frank

**Comment by grabs** [comment]
Hi Frank,

please have a look here: https://github.com/moodlehu/moodle-mod_etherpadlite/issues/38#issuecomment-699681465
This might solve your problem.

Best regards
Andreas

**Comment by bellzebub** [comment]
Is there an easy way to go back to the right 1.8.5 Version? 

ThX a lot
Frank

**Comment by grabs** [comment]
Hi Frank,

You don't have a backup, do you?
As far as I know, it shouldn't be a problem to just check out the right git version. There were no changes in the database structure between this two versions.

Best regards
Andreas

**Comment by bellzebub** [comment]
Okay, I have tried 1.8.4 1.8.5 and 1.8.6 an get every time the same error:-(

I have no more ideas how to solve the problem.
