### ISSUE TITLE
Moodle user names for Etherpad

### ISSUE THREAD

**Issue by CPASimUSante** [moodlehu/moodle-mod_etherpadlite#36]
Would it be possible to have the real Moodle username or better lastname/firstname instead of anonymous "alias" for etherpad : in the case of collective writing assignment, the teacher could evaluate the whole production of the group, but it would be appreciated if he could also compare the contribution of each student with his real name. 

Thanks

**Comment by grabs** [comment]
Hi,
I don't know what version of etherpad-light and/or moodle-plugin do you use. With the current version the users first- and lastname is shown in the pad.
Andreas

**Comment by CPASimUSante** [comment]
Thanks for the reassuring anyways.
Sorry for the partial description. We use Moodle 3.5.8 (not the latest) and etherpad-lite 2019013100 (latest ?). . Would there be any configuration in etherpad-lite / Moodle if I were to use the latest Moodle?

**Comment by grabs** [comment]
Hi,
I am not aware about any settings that change this behavior in either moodle or etherpad lite. But you might check the users who use the etherpad. Are they enrolled in the course or are they are just guests?
Andreas

**Comment by CPASimUSante** [comment]
No they are enrolled in the course.
I think the problem comes from a js error for some reason. But upon examination, i think i can close this issue : it has to do with the installation (i hope) of etherpad-lite itself . The problematic js is absolutely not part of your code. Sorry
