### ISSUE TITLE
Authentication failing with etherpad-lite 1.8.6

### ISSUE THREAD

**Issue by Warudo** [moodlehu/moodle-mod_etherpadlite#38]
I'm using Moodle 3.9.2+ with the most recent release of this addon.

After updating etherpad-lite from 1.8.5 to 1.8.6, I can't access any existing or new pad anymore and the error message displayed is "You do not have permission to access this pad".

Literally the only change is 

- `git checkout v186`

Leads to: "You do not have permission to access this pad" with the following error message being logged:
`[WARN] message - Authentication try failed {"component":"pad","type":"CLIENT_READY","padId":"g.6oQdVkIT8dKFNF4T$SMGpad","sessionID":"s.99101cff3a27b014b0ac358d90064ab1","password":null,"token":"t.au29YLI7iyZs69efNIT0","protocolVersion":2}`
Etherpad still works when accessed directly.

- `git checkout v185`

makes everything work again.

I can switch back and forth between versions and the error on 1.8.6 is reproducible.
No other configuration changes except switching branches and restarting etherpad.

1.8.6. mentions some security fixes in the changelog, maybe it's related to that.

**Comment by grabs** [comment]
Hi Warudo,
this took me a while :(.
Currently there is a bug in the etherpad-lite itself in `src/node/db/SessionManager.js`. The method `findAuthorID()` did not return the AuthorID which led to this error.
At the moment the `develop` version already has this fixed.
So if you use this branch the plugin should work as expected.
Or you work with the version `1.8.5` until there is an update.
Best regards
Andreas
