### ISSUE TITLE
Improve error handling for a misconfigured plugin

### ISSUE THREAD

**Issue by PeaceSfiSh** [moodlehu/moodle-mod_etherpadlite#44]
In our case the wrong API-Key was added to the plugin configuration in Moodle.

The result was the same pad for all activities, like described in Issue #40. An error not explicitly shown as an error.
The padId always was "0" zero, but why?

In _etherpadlite/lib.php_ the plugin:

1. querys the API for a new **groupid** with `$groupid = $instance->create_group();`
2. querys the API for a new **padid** using the 'groupid' with `$instance->create_group_pad($groupid, $config->padname);`
3. adds the **padid** to the database via `$etherpadlite->uri = $padid;` and the insert_record() method

With a wrong or not set API-Key the `$groupid = false` even the `$padid = false`. Remeber the $padid is wiritten to the database, in this case the value **false**, which is casted to "0" while written, for every Moodle activity. 
=> https://my.etherpadlite.service/etherpad/p/0
No exception, no error.

In _etherpadlite/classes/client.php->handle_result()_ the API return codes were checked.

```
switch ($result->code) {
    case self::CODE_OK:
        return $result->data;
    case self::CODE_INVALID_PARAMETERS:
    case self::CODE_INVALID_API_KEY:
        return false;
    case self::CODE_INTERNAL_ERROR:
        return false;
    case self::CODE_INVALID_FUNCTION:
        return false;
    default:
        return false;
}
```

No exceptions thrown, but only **false** will be returned. Here is the place a propper error handling could be implemented trowing exceptions related to the return code of the API.

PS: Maybe there is a relation possible to #26

**Comment by grabs** [comment]
Hi, sorry for the long run.
The last versions in MOODLE_311_STABLE and MOODLE_400_STABLE from today address this issue.
Best regards
Andreas
