### ISSUE TITLE
Every time a create a new Etherpad activity in Moodle I get the same pad

### ISSUE THREAD

**Issue by gerlos** [moodlehu/moodle-mod_etherpadlite#45]
We have a standalone Etherpad server just installed from git that is running fine on the same subdomain of our Moodle 3.11 server. 

We installed this module expecting to be able to get a different pad every time we create a new "Etherpad Lite" activity, but we always get the same pad (/p/0) no matter in which course we add the activity. 

Is this expected, are there any misconfigurations on our side, or is it a bug?

**Comment by grabs** [comment]
Hi,
each activity instance in Moodle should have its own pad. So it is a configuration issue on your site.
Please take a look here: #40 
Maybe there you can find a solution.
