### ISSUE TITLE
Exception when deleting a course with plugin installed but not configured

### ISSUE THREAD

**Issue by lorenzulrich** [moodlehu/moodle-mod_etherpadlite#49]
Deleting a course fails when the mod_etherpadlite plugin is installed but not configured

## Steps to reproduce

* Create a course with an Etherpad (or make sure you have one)
* Remove Etherpad configuration from Moodle configuration
* Try deleting the a course

## Expected behaviour

The course is deleted.

## Current behaviour

An exception is thrown:

![image](https://user-images.githubusercontent.com/1816023/168031240-fdf36a04-e964-4bdb-acc8-d4bbb3752876.png)

I'm not a Moodle expert, but as far as I can see from the stack trace and the code, Moodle tries removing all course items in the trash and also triggers the backup code of mod_etherpadlite. The code at https://github.com/moodlehu/moodle-mod_etherpadlite/blob/master/backup/moodle2/backup_etherpadlite_stepslib.php#L35 doesn't check if there is a configuration for Etherpad, it just tries constructing an instance.

## Moodle info

* Moodle 3.9
* mod_etherpadlite 2021073000 (I don't see any changes relevant to this problem in current Master)

**Comment by grabs** [comment]
Hi, thank you for reporting this!
The last versions in MOODLE_311_STABLE and MOODLE_400_STABLE from today address this issue.
Best regards
Andreas

**Comment by lorenzulrich** [comment]
That's great, thanks for taking care @grabs!
