### ISSUE TITLE
error/could not create etherpad session

### ISSUE THREAD

**Issue by platu** [moodlehu/moodle-mod_etherpadlite#54]
Hello,

I am trying to create pad from mod_etherpadlite v4.0-r2 (2022-06-08) on a Moodle 4.0.2 server instance, and I get the error message : error/could not create etherpad session

The Etherpad version is 1.8.18 (4b96ff6) with parameters set from README.md. The admin page access is functional.

I have 3 LXD containers : mariadb / moodle / etherpad running in the same private VLAN. The Etherpad lite URL set in plugin parameter page is : http://PRIVATE_IP_ADDRESS:9001/

The only debug information I could get was :
```
[Fri Aug 12 15:55:38.858030 2022] [php7:notice] [pid 2685] [client X.X.X.X] Default exception handler: error/could not create etherpad session Debug: \nError code: could not create etherpad session\n$a contents: \n* line 108 of /mod/etherpadlite/view.php: moodle_exception thrown\n, referer: https://moodle.domain/course/view.php?id=2
```
Has anyone already met this problem ?

Thanks in advance for your help,

**Comment by grabs** [comment]
Hi,
sorry for the late response. If you are still on this here my answer.

The `etherpadlite|url` setting should point to the public available etherpad server. As I see in your description you have set a private ip address which will not work at all.
The url you use must match the Moodle domain and also respect the `etherpadlite|cookiedomain` setting.
I would also recommend using HTTPS with valid certificates.

I hope that helps a little.
