### ISSUE TITLE
Moodle 4 monologo doesn't handle white/black lines and areas correctly

### ISSUE THREAD

**Issue by lucaboesch** [moodlehu/moodle-mod_etherpadlite#55]
Although I've submitted a monologo.svg file in https://github.com/moodlehu/moodle-mod_etherpadlite/pull/51 it's evident now that in life action it doesn't behave right.

<img width="657" alt="Etherpad02" src="https://user-images.githubusercontent.com/377279/185215130-342440bd-f3bd-4056-9c47-a6f276777bc9.png">
<img width="239" alt="Etherpad01" src="https://user-images.githubusercontent.com/377279/185215139-9939bc5a-988c-48bc-aac4-535aec7c9214.png">
See in those examples. I would expect white outlines. I wouldn't expect a pure white area.

But I can't manage this myself, my SVG skills are too poor.

Best,
Luca

**Comment by grabs** [comment]
Hi Luca,
sorry for the confusion ;).
In styles.css was a part that disabled the filter for the monologo.
Now that I removed it, the outline is white as it should be ;).
Thanks for the nice logo!

**Comment by lucaboesch** [comment]
Oh, cool, @grabs!
I did not look over there.

Best,
Luca
