### ISSUE TITLE
Moodle 3.11: Call to undefined function mod_etherpadlite_delete_all_mgrouppads()

### ISSUE THREAD

**Issue by lorenzulrich** [moodlehu/moodle-mod_etherpadlite#56]
We're using mod_etherpadlite in version 2022022504 for Moodle 3.11.

Since upgrading to Moodle 3.11, deleting courses through the Moodle webservice throws the following exception:

```
Call to undefined function mod_etherpadlite_delete_all_mgrouppads()
```

The method is located in a file `locallib.php` and called in `lib.php`. I'm not into Moodle development, but I suspect that maybe there were changes in autoloading? Could it be that `locallib.php` is no longer auto-included and therefore the call in `lib.php` fails?

**Comment by grabs** [comment]
Hi,

I went through your descriptions and can not reproduce it all. It looks like there are some files missing or maybe some other issues.
The `locallib.php` isn't loaded automatically. If it is used a `require_once('...');` is called as it is in the `lib.php:etherpadlite_delete_instance()`.
Maybe you can check out the files of the plugin again completely.

Best regards
Andreas

**Comment by lvillanne-recia** [comment]
Hi,

I have the same problem with moodle 3.9

The problem comes from the way the locallib.php file is included.

Currently the include looks like this in file `/mod/etherpadlite/lib.php` at line 144:
```php
function etherpadlite_delete_instance($id) {
    global $DB;
    require_once('locallib.php');
```

To fix the problem, just replace it with:
```php
function etherpadlite_delete_instance($id) {
    global $DB, $CFG;
    require_once($CFG->dirroot.'/mod/etherpadlite/locallib.php');
```

This is how code inclusions are handled in other plugins and indeed doing this in my case fixes the problem.

**Comment by grabs** [comment]
Hi, thank you for this information.
It is fixed now.
Best regards
Andreas
