### ISSUE TITLE
Using a shared etherpad-lite server from several Moodle instances

### ISSUE THREAD

**Issue by ou-li** [moodlehu/moodle-mod_etherpadlite#65]
Possibly not a bug but rather a feature request.

In the above scenario, I sometimes find apparently random users from other Moodle instances in Etherpad's timeslider/list of authors.
Is this expected behaviour?

My hypothesis:
Author IDs probably do not reflect the Moodle instance that Etherpad is being accessed from and are possibly not unique enough to avoid doubles.

Is there any possibility of improving this?

**Comment by grabs** [comment]
Hi,

please check the etherpad setting `etherpadlite | padname`. If you use the same name on different Moodle instances the same namespace is used. Make sure you use different values on this setting.
**But be careful! After the change, you no longer have access to the old pads.**

Best regards
Andreas

**Comment by ou-li** [comment]
Thanks! That should probably fix our problem.
Sounds like a job for the summer break...
