### ISSUE TITLE
Etherpad 1.9.1 Problem: access denied

### ISSUE THREAD

**Issue by robert-thro** [moodlehu/moodle-mod_etherpadlite#66]
Hallo Herr Grabs,

nach Update unserer Moodle-Instanz auf Moodle 4.1 mit Etherpad Lite Plugin (2023061200) und
der Etherpad-Version 1.9.1, kann ich auf bestehenden Pads, die in Moodle 3.9 mit dem Etherpad Lite Plugin (2019013100) 
und Etherpad-Version 1.8.18 erzeugt wurden, zugreifen und auch Änderungen im Pad durchführen. 

Versucht man jedoch neue Pads über das Etherpad Lite Plugin (2023061200) auf Etherpad-Version 1.9.1 anzulegen, werden diese zwar erzeugt, aber man erhält beim Zugriff dann "access denied" auf dem Etherpad-Server bzw. im Plugin "Du hast keine Berechtigung, um auf dieses Pad zuzugreifen".

Folgende Fehlermeldung auf dem Etherpad-Server erscheint:

etherpad_1       | [2023-07-19 13:57:40.926] [ERROR] socket.io - Error handling pad message from 6S**************: Error: access denied
etherpad_1       |     at exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:271:11)
etherpad_1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
etherpad_1       |     at async /opt/etherpad-lite/src/node/handler/SocketIORouter.js:76:14

Sonst keine weiteren Fehlermeldungen.

Haben Sie eine Idee woran das liegen könnte?

Vielen Dank und Grüße
Robert

**Comment by grabs** [comment]
Hi Robert,
sorry for the late response.
I am on it. I will give you more infos as soon as possible.
Andreas

**Comment by grabs** [comment]
Hi Robert,
currently there is a bug in etherpad since version 1.9.x which prevents creating new pads over the api.
There already is a fix which is not applied yet. So I would recommend to use 1.8.x until this is fixed.
https://github.com/ether/etherpad-lite/issues/5787
As this is not a bug of this moodle plugin, I am now closing this issue.
Best regards
Andreas

**Comment by robert-thro** [comment]
Hi Andreas,

thanks a lot for your quick help. Then we hope for a new etherpad version which will fix the problem.

Best regards,
Robert
